[profile.default]
src = "src"
out = "out"
libs = ["lib"]
chain_id = 84532

[rpc_endpoints]
base = "https://sepolia.base.org/"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
